import json
import os
from typing import List, Optional
from groq import Groq
from ..schemas import QueryIntentSchema, RetrievedLoanCaseSchema, FinalResponseSchema
from ..prompts import EXPLANATION_PROMPT, COMPLIANCE_GUIDELINES

class ExplanationAgent:
    def __init__(self, model_name: str = "llama-3.3-70b-versatile", api_key: Optional[str] = None):
        self.model_name = model_name
        self.api_key = api_key or os.getenv('GROQ_API_KEY')
        self.client = None
        if self.api_key:
            try:
                self.client = Groq(api_key=self.api_key)
            except Exception as e:
                print(f"[ERROR] Failed to initialize Groq client: {e}")
                self.client = None
        else:
            print("[WARN] Groq API Key missing. ExplanationAgent will use placeholder logic.")

    def generate_explanation(self, query: str, intent: QueryIntentSchema, cases: List[RetrievedLoanCaseSchema]) -> FinalResponseSchema:
        # Check if this is a conversational/greeting query
        if self._is_conversational_query(query):
            return self._generate_conversational_response(query, intent)
        
        if not self.client or not cases:
            return self._generate_placeholder_response(query, intent, cases)

        # 1. Prepare context
        context_parts = []
        for i, case in enumerate(cases, 1):
            context_parts.append(f"Case {i}: Customer {case.customer_name}, Status: {case.approval_status}, Amount: INR {case.loan_amount}")
            # Add relevant metadata from original_data
            for key in ['Applicant_Income', 'CIBIL_Score', 'Debt_to_Income_Ratio', 'Loan_Purpose']:
                if key in case.original_data:
                    context_parts.append(f"  - {key}: {case.original_data[key]}")
        
        context_str = "\n".join(context_parts)

        # 2. Call LLM
        prompt = EXPLANATION_PROMPT.format(
            query=query,
            intent=intent.intent.value,
            tone=intent.compliance_tone.value,
            context=context_str,
            compliance_guidelines=COMPLIANCE_GUIDELINES
        )

        try:
            response = self.client.chat.completions.create(
                messages=[
                    {"role": "system", "content": "You are a specialized Loan Compliance Analyst."},
                    {"role": "user", "content": prompt}
                ],
                model=self.model_name,
                temperature=0.1,
                response_format={"type": "json_object"}
            )
            
            data = json.loads(response.choices[0].message.content)
            
            return FinalResponseSchema(
                query=query,
                intent=intent.intent,
                retrieved_case_count=len(cases),
                summary=data.get("summary", "Analysis complete."),
                evidence_points=data.get("evidence_points", []),
                risk_notes=data.get("risk_notes", []),
                compliance_disclaimer=data.get("compliance_disclaimer", "Generated by AI. Verify with official records."),
                structured_data=cases
            )

        except Exception as e:
            print(f"[ERROR] ExplanationAgent LLM Error: {e}")
            return self._generate_placeholder_response(query, intent, cases)

    def _generate_placeholder_response(self, query: str, intent: QueryIntentSchema, cases: List[RetrievedLoanCaseSchema]) -> FinalResponseSchema:
        if not cases:
            return FinalResponseSchema(
                query=query,
                intent=intent.intent,
                retrieved_case_count=0,
                summary="No relevant historical cases found matching your query.",
                evidence_points=[],
                risk_notes=["Try broadening your search criteria."],
                compliance_disclaimer="Generated by AI (Fallback Mode).",
                structured_data=[]
            )

        # Analyze cases manually
        total = len(cases)
        approved = sum(1 for c in cases if c.approval_status == 'Approved')
        rejected = total - approved
        approval_rate = (approved / total) * 100
        
        # Extract common patterns from original data (with safe type conversion)
        def safe_float(value, default=0):
            try:
                return float(value) if value else default
            except (ValueError, TypeError):
                return default
        
        avg_cibil = sum(safe_float(c.original_data.get('CIBIL_Score')) for c in cases) / total
        avg_income = sum(safe_float(c.original_data.get('Applicant_Income')) for c in cases) / total
        
        # Construct a rich summary
        summary = (
            f"Based on {total} similar historical case(s), the approval rate is {approval_rate:.1f}%. "
            f"The candidates had an average CIBIL score of {avg_cibil:.0f} and average income of INR {avg_income:,.0f}. "
            f"{'Most cases were rejected.' if rejected > approved else 'Most cases were approved.'}"
        )

        # Generate evidence points
        evidence_points = []
        for c in cases[:5]:
            status_icon = "âœ…" if c.approval_status == 'Approved' else "âŒ"
            evidence_points.append(
                f"{status_icon} Case: {c.customer_name} ({c.approval_status}) - CIBIL: {c.original_data.get('CIBIL_Score', 'N/A')}, Income: {c.original_data.get('Applicant_Income', 'N/A')}"
            )

        # Generate risk notes based on rejected cases
        risk_notes = []
        rejected_cases = [c for c in cases if c.approval_status == 'Rejected']
        if rejected_cases:
            risk_notes.append("Common factors in rejected cases:")
            # Check simple thresholds (heuritics)
            low_cibil = sum(1 for c in rejected_cases if safe_float(c.original_data.get('CIBIL_Score')) < 750)
            if low_cibil > 0:
                risk_notes.append(f"â€¢ Low CIBIL Score (<750) observed in {low_cibil} rejected cases.")
            
            high_loan = sum(1 for c in rejected_cases if safe_float(c.original_data.get('Loan_Amount')) > 5000000)
            if high_loan > 0:
                risk_notes.append(f"â€¢ High Loan Amount (>50L) observed in {high_loan} rejected cases.")
        else:
            risk_notes.append("No significant risk factors detected in the retrieved similar cases (mostly approved).")
        
        return FinalResponseSchema(
            query=query,
            intent=intent.intent,
            retrieved_case_count=len(cases),
            summary=summary,
            evidence_points=evidence_points,
            risk_notes=risk_notes,
            compliance_disclaimer="Generated by Case Analysis Engine (Fallback Mode). Verify with official records.",
            structured_data=cases
        )
    
    def _is_conversational_query(self, query: str) -> bool:
        """Detect if query is conversational/greeting rather than loan-related"""
        query_lower = query.lower().strip()
        
        # Common greetings and conversational patterns
        conversational_patterns = [
            'hello', 'hi', 'hey', 'greetings', 'good morning', 'good afternoon', 
            'good evening', 'how are you', 'what\'s up', 'whats up', 'sup',
            'thanks', 'thank you', 'bye', 'goodbye', 'see you', 'ok', 'okay',
            'yes', 'no', 'maybe', 'help', 'who are you', 'what can you do'
        ]
        
        # Check if query is very short and matches conversational patterns
        if len(query_lower.split()) <= 3:
            for pattern in conversational_patterns:
                if pattern in query_lower:
                    return True
        
        # Check if query doesn't contain any loan-related keywords
        loan_keywords = [
            'loan', 'credit', 'cibil', 'approve', 'reject', 'application',
            'amount', 'income', 'debt', 'risk', 'case', 'similar', 'why',
            'status', 'purpose', 'home', 'personal', 'business', 'education'
        ]
        
        has_loan_keyword = any(keyword in query_lower for keyword in loan_keywords)
        
        # If very short query with no loan keywords, treat as conversational
        if len(query_lower.split()) <= 5 and not has_loan_keyword:
            return True
        
        return False
    
    def _generate_conversational_response(self, query: str, intent: QueryIntentSchema) -> FinalResponseSchema:
        """Generate friendly conversational response"""
        query_lower = query.lower().strip()
        
        # Determine appropriate response
        if any(word in query_lower for word in ['hello', 'hi', 'hey', 'greetings']):
            summary = "Hello! I'm your Loan Insight Assistant. I can help you analyze loan applications, understand approval/rejection patterns, and provide insights based on historical data. How can I assist you today?"
        elif any(word in query_lower for word in ['how are you', 'what\'s up', 'whats up']):
            summary = "I'm functioning well, thank you! I'm here to help you with loan-related queries. You can ask me about loan approvals, rejections, risk analysis, or similar cases."
        elif any(word in query_lower for word in ['thanks', 'thank you']):
            summary = "You're welcome! Feel free to ask if you have any other loan-related questions."
        elif any(word in query_lower for word in ['bye', 'goodbye', 'see you']):
            summary = "Goodbye! Have a great day. Come back anytime you need loan insights!"
        elif any(word in query_lower for word in ['help', 'what can you do', 'who are you']):
            summary = """I'm your Loan Insight Assistant powered by AI. I can help you with:

• Analyzing why loans were approved or rejected
• Finding similar loan cases based on criteria
• Identifying risk factors in applications
• Providing compliance-friendly explanations
• Generating insights from historical loan data

Try asking questions like:
- "Why was loan L12345 rejected?"
- "Show me similar approved cases for home loans"
- "What are common risk factors in rejected applications?"
- "Analyze loans with CIBIL score below 700"
"""
        else:
            summary = "I'm here to help with loan-related queries. Please ask me about loan approvals, rejections, risk analysis, or similar cases from our historical data."
        
        return FinalResponseSchema(
            query=query,
            intent=intent.intent,
            retrieved_case_count=0,
            summary=summary,
            evidence_points=[],
            risk_notes=[],
            compliance_disclaimer="This is a conversational response. For loan analysis, please ask specific loan-related questions.",
            structured_data=[]
        )

